name: CI Pipeline with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build images using Docker Compose
      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build

      # Run tests in Docker container
      - name: Run tests
        run: |
          docker-compose -f docker-compose.yml up -d
          docker-compose -f docker-compose.yml exec -T web pytest
          docker-compose down

      # Deploy to production (this step can be customized as needed)
      - name: Deploy to production
        run: |
          docker-compose -f docker-compose.yml up -d
